### ISSUE TITLE
support addressing excel sheets

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-data-embed#118]
**Is your feature request related to a problem? Please describe.**
currently it is not possible to address a specific sheet in an excel workbook. Further it is not possible to define which sheet should be the default.

**Describe the solution you'd like**
use a query parameter, eg `sheet=` to select the sheet to fetch. in order to make it impossible to fetch sheets that are considered 'private', only sheets with `helix-` or `helix_` prefix should be addressable.
furthermore, if there is a sheet names `helix-default` or `helix_default`, it should be used instead of the first sheet.

/cc @trieloff @davidnuescheler

**Comment by tripodsan** [comment]
Similar to the sheet-names, that same should be applied to table names.

**Comment by davidnuescheler** [comment]
i don't know that addressing sheets really is the correct approach, especially if we consider that there should be information in the excel or google sheet document that should not be exposed. however, instead of (or in addition to) the default behavior of serving the first sheet we should serve a sheet with a specific name, for example `helix output` or similar.

using the first sheet is largely problematic for a couple of reasons:

(1) in real life there are usually a number of sheets in a "workbook" (to use excel terminology) and some of them will be manipulated by humans. in those cases the sheet that is output to helix is normally not the one for humans to make changes to. so from a sort order perspective the sheet that helix pulls should definitely not be the first (and possibly should even be hidden in some cases) as it really obstructs the human editor to get to the sheet that they can and should make changes to.

(2) there have been a number of incidents where someone moved a sheet by changing the sheet sort order resulting in a completely different json payload. this can yield catastrophic results depending on how material access to a specific json with a specific structure is for a particular website.

**Comment by tripodsan** [comment]
exactly what I wrote in the description above :-)
